# Build stage
FROM node:20-alpine AS builder
WORKDIR /app
ARG VITE_API_URL=http://localhost:4000
ARG VITE_PHP_API_URL=https://crm.thinhgialand.com
ENV VITE_API_URL=$VITE_API_URL
ENV VITE_PHP_API_URL=$VITE_PHP_API_URL
COPY package*.json ./
RUN npm install
COPY . .
RUN npm run build

# Production stage using a lightweight web server
FROM nginx:stable-alpine
COPY --from=builder /app/dist /usr/share/nginx/html
# Copy a custom nginx config if you have one
# COPY nginx.conf /etc/nginx/conf.d/default.conf
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]
